import type { TripPlan } from '../../types'

interface Props { plan: TripPlan }

const getCategoryIcon = (key: string) => {
  const normalized = (key || '').toLowerCase().replace(/_/g, ' ')
  if (normalized.includes('flight') || normalized.includes('air')) return '✈️'
  if (normalized.includes('accommodation') || normalized.includes('hotel') || normalized.includes('stay') || normalized.includes('lodging')) return '🏨'
  if (normalized.includes('food') || normalized.includes('meal') || normalized.includes('restaurant') || normalized.includes('dining')) return '🍜'
  if (normalized.includes('local transport') || normalized.includes('transit') || normalized.includes('cabs') || normalized.includes('transport')) return '🚆'
  if (normalized.includes('activities') || normalized.includes('entry') || normalized.includes('fee') || normalized.includes('ticket') || normalized.includes('attractions')) return '🎟️'
  if (normalized.includes('shopping') || normalized.includes('misc')) return '🛍️'
  if (normalized.includes('visa') || normalized.includes('insurance')) return '🛂'
  if (normalized.includes('emergency') || normalized.includes('buffer')) return '🛡️'
  return '•'
}

export default function BudgetSection({ plan }: Props) {
  const { budget, flights, hotels, food, request: req } = plan
  const baseBreakdown = budget?.breakdown || {}
  const savingsTips = budget?.savings_tips || []
  
  // Synchronize actual costs generated by specialized agents
  const breakdown = { ...baseBreakdown }
  
  if (flights?.estimated_cost_inr > 0) {
    const key = Object.keys(breakdown).find(k => k.toLowerCase().includes('transport') || k.toLowerCase().includes('flight')) || 'transportation'
    breakdown[key] = flights.estimated_cost_inr
  }
  
  if (hotels?.estimated_total_cost_inr > 0) {
    const key = Object.keys(breakdown).find(k => k.toLowerCase().includes('accommodation') || k.toLowerCase().includes('hotel')) || 'accommodation'
    breakdown[key] = hotels.estimated_total_cost_inr
  }
  
  if (food?.estimated_daily_food_cost_inr > 0 && req?.duration_days > 0) {
    const key = Object.keys(breakdown).find(k => k.toLowerCase().includes('food') || k.toLowerCase().includes('meal')) || 'food_and_activities'
    // Usually LLM generates daily food cost per group. If it's too low, we just trust the number they output times days.
    const trueFoodCost = food.estimated_daily_food_cost_inr * req.duration_days
    breakdown[key] = trueFoodCost
  }

  const total = Object.values(breakdown).reduce((a, b) => a + b, 0)

  if (Object.keys(breakdown).length === 0 && savingsTips.length === 0 && !budget?.feasibility_note) {
    return null
  }

  return (
    <div className="card h-full flex flex-col overflow-y-auto min-w-0 break-words">
      <h2 className="text-2xl font-bold text-white tracking-tight mb-5">💰 Budget Breakdown</h2>

      {budget?.feasibility_note && (
        <div className={`mb-4 rounded-2xl p-4 border flex gap-4 items-start shadow-sm ${budget?.is_feasible ? 'bg-[#172033] border-green-500/20' : 'bg-[#1c1635] border-red-500/20'}`}>
          <div className={`w-10 h-10 rounded-xl flex items-center justify-center text-xl shrink-0 ${budget?.is_feasible ? 'bg-green-500/10 text-green-400' : 'bg-red-500/10 text-red-400'}`}>
             {budget?.is_feasible ? '✅' : '⚠️'}
          </div>
          <div className="flex-1">
             <h3 className="font-bold text-white leading-tight mb-1">Feasibility</h3>
             <p className="text-sm text-white/70 leading-relaxed">{budget?.feasibility_note}</p>
          </div>
        </div>
      )}

      <div className="space-y-3">
        {Object.entries(breakdown).map(([key, val]) => {
          const pct = total > 0 ? (val / total) * 100 : 0
          return (
            <div key={key} className="bg-[#172033] rounded-2xl p-4 border border-white/5 flex gap-4 items-center shadow-sm">
              <div className="w-10 h-10 rounded-xl bg-[#202b40] flex items-center justify-center text-xl shrink-0">
                {getCategoryIcon(key)}
              </div>
              <div className="flex-1">
                <div className="flex justify-between text-sm mb-1">
                  <span className="font-bold text-white leading-tight capitalize">{key.replace(/_/g, ' ')}</span>
                  <span className="text-[#4cd7f6] font-bold">₹{val.toLocaleString('en-IN')}</span>
                </div>
                <div className="h-1.5 bg-[#202b40] rounded-full overflow-hidden mt-2">
                  <div className="h-full bg-[#4cd7f6] rounded-full" style={{ width: `${pct}%` }} />
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {total > 0 && (
        <div className="mt-5 pt-4 border-t border-white/5 flex justify-between font-bold items-center">
          <span className="text-white/80">Total estimated</span>
          <span className={`text-xl ${total > (budget?.total_budget_inr || 0) ? 'text-[#ffb4ab]' : 'text-[#4cd7f6]'}`}>
            ₹{total.toLocaleString('en-IN')}
          </span>
        </div>
      )}

      {req?.num_travelers > 0 && req?.duration_days > 0 && total > 0 && (
        <p className="text-sm font-semibold text-[#d2bbff] mt-2 text-right">
          ≈ ₹{Math.round(total / (req.num_travelers * req.duration_days)).toLocaleString('en-IN')} per person/day
        </p>
      )}

      {savingsTips.length > 0 && (
        <div className="mt-6 space-y-2">
          <p className="text-xs text-white/50 font-bold uppercase tracking-wider mb-2">Savings tips</p>
          {savingsTips.map((tip, i) => (
            <p key={i} className="text-sm text-white/70 flex items-start gap-2 leading-relaxed">
              <span className="text-[#4cd7f6] mt-0.5">•</span> <span>{tip}</span>
            </p>
          ))}
        </div>
      )}
    </div>
  )
}
