import type { TripPlan } from '../types'

export function exportPlanToPdf(plan: TripPlan) {
  const iframe = document.createElement('iframe')
  iframe.style.position = 'fixed'
  iframe.style.right = '0'
  iframe.style.bottom = '0'
  iframe.style.width = '0'
  iframe.style.height = '0'
  iframe.style.border = '0'
  document.body.appendChild(iframe)

  const doc = iframe.contentWindow?.document || iframe.contentDocument
  if (!doc) return

  const req = plan.request
  const destCurrency = plan.currency.dest_currency_code || 'JPY'
  const exchangeRate = plan.currency.inr_to_dest_rate || plan.currency.inr_to_jpy_rate || 1
  const localBudget = plan.currency.budget_in_dest_currency || plan.currency.budget_in_jpy || 0
  const localDailyBudget = plan.currency.daily_budget_dest_currency || plan.currency.daily_budget_jpy || 0

  // Build a highly structured, clean printable HTML document
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Trip Itinerary - ${req.destination}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            padding: 40px;
            font-size: 14px;
            background: #ffffff;
          }
          h1 {
            font-size: 32px;
            color: #0f172a;
            margin-bottom: 5px;
            border-bottom: 3px solid #7c3aed;
            padding-bottom: 12px;
            font-weight: 800;
          }
          h2 {
            font-size: 20px;
            color: #1e3a8a;
            margin-top: 35px;
            margin-bottom: 15px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 6px;
            page-break-after: avoid;
            font-weight: 700;
          }
          h3 {
            font-size: 16px;
            color: #0f172a;
            margin-top: 20px;
            margin-bottom: 10px;
            page-break-after: avoid;
            font-weight: 600;
          }
          p { margin: 0 0 12px 0; }
          .meta-info {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            border: 1px solid #e2e8f0;
          }
          .meta-item strong { color: #475569; }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          th, td {
            border: 1px solid #cbd5e1;
            padding: 10px 12px;
            text-align: left;
          }
          th {
            background-color: #f1f5f9;
            color: #1e293b;
            font-weight: 600;
          }
          ul {
            margin: 0 0 25px 0;
            padding-left: 20px;
          }
          li { margin-bottom: 6px; }
          .page-break {
            page-break-before: always;
          }
          .badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 12px;
            font-weight: 600;
          }
          .badge-feasible {
            background: #dcfce7;
            color: #15803d;
          }
          .badge-tight {
            background: #fee2e2;
            color: #b91c1c;
          }
          .itinerary-day {
            margin-bottom: 20px;
            padding: 16px;
            background: #f8fafc;
            border-left: 4px solid #7c3aed;
            border-radius: 0 8px 8px 0;
            page-break-inside: avoid;
          }
          .itinerary-day h4 {
            margin: 0 0 10px 0;
            color: #0f172a;
            font-size: 16px;
            font-weight: 700;
          }
          .activity {
            margin-bottom: 8px;
          }
          .activity strong {
            color: #475569;
          }
          @media print {
            body { padding: 15px; font-size: 12px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <h1>Trip Plan: ${req.destination}</h1>
        <p style="color: #64748b; margin-bottom: 25px;">Generated by Smart Journey</p>
        
        <div class="meta-info">
          <div class="meta-item"><strong>Origin:</strong> ${req.origin}</div>
          <div class="meta-item"><strong>Duration:</strong> ${req.duration_days} Days (${req.travel_month})</div>
          <div class="meta-item"><strong>Travelers:</strong> ${req.num_travelers}</div>
          <div class="meta-item"><strong>Original Budget:</strong> ₹${req.budget_inr.toLocaleString('en-IN')}</div>
          <div class="meta-item">
            <strong>Budget Status:</strong> 
            <span class="badge ${plan.budget.is_feasible ? 'badge-feasible' : 'badge-tight'}">
              ${plan.budget.is_feasible ? 'Feasible' : 'Tight / Over Budget'}
            </span>
          </div>
          <div class="meta-item"><strong>Interests:</strong> ${req.interests.join(', ') || 'General'}</div>
        </div>

        <h2>💰 Trip Budget & Expenses</h2>
        <p><strong>Feasibility Assessment:</strong> ${plan.budget.feasibility_note}</p>
        <p><strong>Estimated Cost Per Person Per Day:</strong> ₹${Math.round(plan.budget.per_person_per_day_inr).toLocaleString('en-IN')}</p>
        
        <table>
          <thead>
            <tr>
              <th>Expense Category</th>
              <th>Estimated Cost (INR)</th>
            </tr>
          </thead>
          <tbody>
            ${Object.entries(plan.budget.breakdown).map(([category, amount]) => `
              <tr>
                <td style="text-transform: capitalize;">${category.replace('_', ' ')}</td>
                <td>₹${Math.round(amount).toLocaleString('en-IN')}</td>
              </tr>
            `).join('')}
            <tr style="font-weight: bold; background: #f8fafc;">
              <td>Total Estimated Cost</td>
              <td>₹${Math.round(Object.values(plan.budget.breakdown).reduce((a, b) => a + b, 0)).toLocaleString('en-IN')}</td>
            </tr>
          </tbody>
        </table>

        <h3>💡 Savings & Budget Tips</h3>
        <ul>
          ${plan.budget.savings_tips.map(tip => `<li>${tip}</li>`).join('')}
        </ul>

        <div class="page-break"></div>

        <h2>🚆 Transportation & Transit</h2>
        <p><strong>Recommended Routes:</strong></p>
        <ul>
          ${plan.flights.recommended_routes.map(route => `<li>${route}</li>`).join('')}
        </ul>
        <p><strong>Suggested Carriers & Providers:</strong> ${plan.flights.airlines.join(', ')}</p>
        <p><strong>Estimated Total Flight Cost:</strong> ₹${Math.round(plan.flights.estimated_cost_inr).toLocaleString('en-IN')}</p>
        <h3>💡 Flight Booking Tips</h3>
        <ul>
          ${plan.flights.tips.map(tip => `<li>${tip}</li>`).join('')}
        </ul>

        <h2>🏨 Accommodation & Hotels</h2>
        <table>
          <thead>
            <tr>
              <th>Hotel Name</th>
              <th>Location</th>
              <th>Type</th>
              <th>Rating</th>
              <th>Est. Price/Night</th>
            </tr>
          </thead>
          <tbody>
            ${plan.hotels.recommendations.map(hotel => `
              <tr>
                <td><strong>${hotel.name}</strong></td>
                <td>${hotel.location}</td>
                <td>${hotel.type}</td>
                <td>${hotel.rating}</td>
                <td>₹${Math.round(hotel.price_per_night_inr).toLocaleString('en-IN')}</td>
              </tr>
              <tr>
                <td colspan="5" style="font-size: 12px; color: #475569; background: #fafafa; border-bottom: 2px solid #cbd5e1;">
                  <em>Why recommend:</em> ${hotel.why}
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p><strong>Estimated Total Lodging Cost:</strong> ₹${Math.round(plan.hotels.estimated_total_cost_inr).toLocaleString('en-IN')}</p>
        <h3>💡 Accommodation Tips</h3>
        <ul>
          ${plan.hotels.tips.map(tip => `<li>${tip}</li>`).join('')}
        </ul>

        <div class="page-break"></div>

        <h2>🛂 Visa Requirements</h2>
        <p><strong>Visa Required:</strong> ${plan.visa.visa_required ? 'Yes' : 'No'}</p>
        <p><strong>Visa Type:</strong> ${plan.visa.visa_type}</p>
        <p><strong>Processing Time:</strong> ${plan.visa.processing_time}</p>
        <p><strong>Estimated Fee:</strong> ₹${Math.round(plan.visa.estimated_fee_inr).toLocaleString('en-IN')}</p>
        
        <h3>📝 Required Documents</h3>
        <ul>
          ${plan.visa.required_documents.map(doc => `<li>${doc}</li>`).join('')}
        </ul>
        
        <h3>👣 Application Steps</h3>
        <ol>
          ${plan.visa.application_steps.map(step => `<li>${step}</li>`).join('')}
        </ol>

        <h2>🍜 Food & Dining</h2>
        <p><strong>Daily Food Budget Estimate:</strong> ₹${Math.round(plan.food.estimated_daily_food_cost_inr).toLocaleString('en-IN')} per person</p>
        <h3>🍱 Must-Try Dishes</h3>
        <ul>
          ${plan.food.must_try_dishes.map(dish => `<li>${dish}</li>`).join('')}
        </ul>
        <h3>🍽️ Recommended Restaurants</h3>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Cuisine & Specialty</th>
              <th>Location</th>
              <th>Est. Price/Meal</th>
            </tr>
          </thead>
          <tbody>
            ${plan.food.restaurant_recommendations.map(rest => `
              <tr>
                <td><strong>${rest.name}</strong><br/><span style="font-size: 11px; color: #64748b;">${rest.why}</span></td>
                <td>${rest.cuisine} (${rest.specialty})</td>
                <td>${rest.location}</td>
                <td>₹${Math.round(rest.price_per_meal_inr).toLocaleString('en-IN')}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="page-break"></div>

        <h2>📅 Detailed Daily Itinerary</h2>
        ${plan.itinerary.days.map(day => `
          <div class="itinerary-day">
            <h4>Day ${day.day} - ${day.date_note} (${day.city})</h4>
            <div class="activity"><strong>Morning:</strong> ${day.morning}</div>
            <div class="activity"><strong>Afternoon:</strong> ${day.afternoon}</div>
            <div class="activity"><strong>Evening:</strong> ${day.evening}</div>
            <div class="activity" style="margin-top: 10px; font-size: 12px; color: #64748b;">
              <strong>Estimated Daily Expenses:</strong> ₹${Math.round(day.estimated_cost_inr).toLocaleString('en-IN')} | 
              <strong>Highlights:</strong> ${day.highlights.join(', ')}
            </div>
          </div>
        `).join('')}

        <h3>🌧️ Wet Weather Contingency Plan</h3>
        <p>${plan.itinerary.rain_alternative_plan}</p>

        <div class="page-break"></div>

        <h2>💱 Currency & Money Details</h2>
        <p><strong>Exchange Rate:</strong> 1 INR = ${exchangeRate} ${destCurrency}</p>
        <p><strong>Total Budget in Local Currency:</strong> ${Math.round(localBudget).toLocaleString()} ${destCurrency}</p>
        <p><strong>Daily Spending Limit:</strong> ${Math.round(localDailyBudget).toLocaleString()} ${destCurrency}</p>
        
        <h3>💡 Cash & Payment Advice</h3>
        <ul>
          ${plan.currency.payment_tips.map(tip => `<li>${tip}</li>`).join('')}
        </ul>

        <h2>🌤️ Weather Outlook</h2>
        <p><strong>Overview:</strong> ${plan.weather.monthly_overview}</p>
        <p><strong>Summary:</strong> ${plan.weather.summary}</p>
        
        <h3>🌡️ Outlook Summary</h3>
        <ul>
          ${plan.weather.daily_forecast.map(dayForecast => `<li>${dayForecast}</li>`).join('')}
        </ul>

        <h2>🚆 Transit & Route Logistics</h2>
        <p><strong>Optimal Route Order:</strong> ${plan.route.optimal_city_order.join(' → ')}</p>
        
        <h3>Transit Connections</h3>
        <table>
          <thead>
            <tr>
              <th>From</th>
              <th>To</th>
              <th>Transport Mode</th>
              <th>Duration</th>
              <th>Est. Cost</th>
            </tr>
          </thead>
          <tbody>
            ${plan.route.transport_between_cities.map(leg => `
              <tr>
                <td>${leg.from}</td>
                <td>${leg.to}</td>
                <td>${leg.mode}</td>
                <td>${leg.duration}</td>
                <td>₹${Math.round(leg.cost_inr).toLocaleString('en-IN')}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <h3>🎒 Packing Checklist & Highlights</h3>
        <ul>
          ${plan.packing_list.map(item => `<li>${item}</li>`).join('')}
        </ul>
      </body>
    </html>
  `

  doc.open()
  doc.write(html)
  doc.close()

  // Wait for rendering and trigger print
  setTimeout(() => {
    iframe.contentWindow?.focus()
    iframe.contentWindow?.print()
    setTimeout(() => {
      document.body.removeChild(iframe)
    }, 1000)
  }, 500)
}
